CREATE TABLE IF NOT EXISTS educator_invite_tokens (
    invite_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    invite_uuid VARCHAR(36) NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    expires_at DATETIME NOT NULL,
    used_at DATETIME NULL,
    used_by_user_id BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_educator_invite_tokens_uuid UNIQUE (invite_uuid),
    CONSTRAINT uq_educator_invite_tokens_hash UNIQUE (token_hash),
    CONSTRAINT fk_educator_invite_tokens_creator FOREIGN KEY (created_by_user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_educator_invite_tokens_used_by FOREIGN KEY (used_by_user_id) REFERENCES users (user_id) ON DELETE SET NULL
) COMMENT='One-time educator invite tokens generated by admins for direct educator registration.';
