from __future__ import annotations

from app.services.providers.types import ModelDefinition, ModelProviderDefinition


SUPPORTED_PROVIDER_KEYS = {"gemini", "glm", "openrouter"}

PROVIDER_DEFINITIONS: tuple[ModelProviderDefinition, ...] = (
    ModelProviderDefinition("gemini", "Gemini", "gemini", None, True, 10),
    ModelProviderDefinition("glm", "GLM", "openai_compatible", "https://open.bigmodel.cn/api/paas/v4", True, 20),
    ModelProviderDefinition(
        "openrouter",
        "OpenRouter",
        "openai_compatible",
        "https://openrouter.ai/api/v1",
        True,
        30,
        require_json_parameter_support=True,
    ),
)

MODEL_DEFINITIONS: tuple[ModelDefinition, ...] = (
    ModelDefinition(
        "gemini:gemini-3.5-flash-lite",
        "gemini",
        "gemini-3.5-flash-lite",
        "Gemini 3.5 Flash-Lite",
        True,
        False,
        True,
        True,
        False,
        True,
        False,
        display_order=10,
        paired_embedding_model_id="gemini:gemini-embedding-2",
    ),
    ModelDefinition(
        "gemini:gemini-3.6-flash",
        "gemini",
        "gemini-3.6-flash",
        "Gemini 3.6 Flash",
        True,
        False,
        True,
        True,
        False,
        True,
        False,
        display_order=11,
        paired_embedding_model_id="gemini:gemini-embedding-2",
    ),
    ModelDefinition(
        "gemini:gemini-embedding-2",
        "gemini",
        "gemini-embedding-2",
        "Gemini Embedding 2",
        True,
        False,
        False,
        False,
        True,
        False,
        True,
        embedding_dimension=1024,
        display_order=19,
    ),
    ModelDefinition(
        "glm:glm-4.7",
        "glm",
        "glm-4.7",
        "GLM 4.7",
        True,
        False,
        True,
        True,
        False,
        True,
        False,
        display_order=21,
        paired_embedding_model_id="glm:embedding-3",
    ),
    ModelDefinition(
        "glm:embedding-3",
        "glm",
        "embedding-3",
        "GLM Embedding-3",
        True,
        False,
        False,
        False,
        True,
        False,
        True,
        embedding_dimension=1024,
        display_order=29,
    ),
    ModelDefinition(
        "openrouter:openrouter/auto",
        "openrouter",
        "openrouter/auto",
        "OpenRouter Auto",
        True,
        False,
        True,
        True,
        False,
        True,
        False,
        display_order=30,
        paired_embedding_model_id="openrouter:openai/text-embedding-3-small",
    ),
    ModelDefinition(
        "openrouter:openai/text-embedding-3-small",
        "openrouter",
        "openai/text-embedding-3-small",
        "OpenAI Text Embedding 3 Small via OpenRouter",
        True,
        False,
        False,
        False,
        True,
        False,
        True,
        embedding_dimension=1024,
        display_order=39,
    ),
)

MODEL_DEFINITION_BY_ID = {model.model_id: model for model in MODEL_DEFINITIONS}
PROVIDER_DEFINITION_BY_KEY = {provider.provider_key: provider for provider in PROVIDER_DEFINITIONS}
