from __future__ import annotations

from app.services.providers.types import ModelDefinition, ModelProviderDefinition


SUPPORTED_PROVIDER_KEYS = {"gemini", "deepseek", "glm", "openrouter"}

PROVIDER_DEFINITIONS: tuple[ModelProviderDefinition, ...] = (
    ModelProviderDefinition("gemini", "Gemini", "gemini", None, True, 10),
    ModelProviderDefinition("deepseek", "DeepSeek", "openai_compatible", "https://api.deepseek.com", True, 20),
    ModelProviderDefinition("glm", "GLM", "openai_compatible", "https://open.bigmodel.cn/api/paas/v4", True, 30),
    ModelProviderDefinition("openrouter", "OpenRouter", "openai_compatible", "https://openrouter.ai/api/v1", True, 40),
)

MODEL_DEFINITIONS: tuple[ModelDefinition, ...] = (
    ModelDefinition(
        "gemini:gemini-2.5-flash-lite",
        "gemini",
        "gemini-2.5-flash-lite",
        "Gemini 2.5 Flash Lite",
        True,
        False,
        True,
        True,
        False,
        True,
        False,
        display_order=10,
    ),
    ModelDefinition(
        "gemini:gemini-2.5-flash",
        "gemini",
        "gemini-2.5-flash",
        "Gemini 2.5 Flash",
        True,
        False,
        True,
        True,
        False,
        True,
        False,
        display_order=11,
    ),
    ModelDefinition(
        "gemini:gemini-2.5-pro",
        "gemini",
        "gemini-2.5-pro",
        "Gemini 2.5 Pro",
        True,
        False,
        True,
        True,
        False,
        True,
        False,
        display_order=12,
    ),
    ModelDefinition(
        "gemini:gemini-embedding-001",
        "gemini",
        "gemini-embedding-001",
        "Gemini Embedding 001",
        True,
        False,
        False,
        False,
        True,
        False,
        True,
        embedding_dimension=1536,
        display_order=19,
    ),
    ModelDefinition(
        "deepseek:deepseek-v4-flash",
        "deepseek",
        "deepseek-v4-flash",
        "DeepSeek V4 Flash",
        True,
        False,
        True,
        True,
        False,
        True,
        False,
        display_order=20,
    ),
    ModelDefinition(
        "glm:glm-4.5-air",
        "glm",
        "glm-4.5-air",
        "GLM 4.5 Air",
        True,
        False,
        True,
        True,
        False,
        True,
        False,
        display_order=30,
    ),
    ModelDefinition(
        "glm:glm-4.7",
        "glm",
        "glm-4.7",
        "GLM 4.7",
        True,
        False,
        True,
        True,
        False,
        True,
        False,
        display_order=31,
    ),
    ModelDefinition(
        "openrouter:openrouter/auto",
        "openrouter",
        "openrouter/auto",
        "OpenRouter Auto",
        True,
        False,
        True,
        True,
        False,
        True,
        False,
        display_order=40,
    ),
    ModelDefinition(
        "openrouter:google/gemini-2.5-flash",
        "openrouter",
        "google/gemini-2.5-flash",
        "Gemini 2.5 Flash via OpenRouter",
        True,
        False,
        True,
        True,
        False,
        True,
        False,
        display_order=41,
    ),
)

MODEL_DEFINITION_BY_ID = {model.model_id: model for model in MODEL_DEFINITIONS}
PROVIDER_DEFINITION_BY_KEY = {provider.provider_key: provider for provider in PROVIDER_DEFINITIONS}
