import { useCallback, useEffect, useRef, useState } from "react";
import { Navigate, useOutletContext, useParams } from "react-router-dom";

import {
  createAutoGeneratedQuizAttemptRun,
  getActiveAutoGeneratedQuizAttemptRun,
  getAutoGeneratedQuizAttemptRun,
  getActiveQuizSession,
  getQuizAttemptDetail,
  getQuizAttemptHistory,
  startQuizAttempt,
  submitQuizAttempt,
} from "../../services/course";
import type {
  QuizAttemptHistory,
  QuizAttemptResult,
  QuizAttemptSession,
  QuizGenerationProgressEvent,
  QuizGenerationRun,
  QuizSessionQuestion,
} from "../../types/course";
import { emitAppRefresh } from "../../utils/refreshEvents";
import type { CourseOutletContext } from "./CourseLayout";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function formatDuration(seconds: number | null): string {
  if (!seconds) return "—";
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return m > 0 ? `${m}m ${s}s` : `${s}s`;
}

function formatDate(iso: string): string {
  try {
    return new Date(iso).toLocaleString();
  } catch {
    return iso;
  }
}

function getGenerationStepLabel(step: string | null | undefined) {
  switch (step) {
    case "load_inputs":
      return "Preparing quiz";
    case "retrieve_context":
      return "Retrieving module context";
    case "plan_quiz":
      return "Planning quiz";
    case "generate_quiz":
      return "Generating questions";
    case "validate_quiz":
      return "Validating questions";
    case "publish_quiz":
      return "Saving questions";
    case "start_generated_attempt":
      return "Starting quiz";
    default:
      return "Generating quiz";
  }
}

// ---------------------------------------------------------------------------
// Timer bar
// ---------------------------------------------------------------------------

function TimerBar({ totalSeconds, remainingSeconds }: { totalSeconds: number; remainingSeconds: number }) {
  const pct = Math.max(0, Math.min(100, (remainingSeconds / totalSeconds) * 100));
  const isWarning = pct < 25;
  return (
    <div className="quiz-timer-bar-wrap">
      <div
        className={`quiz-timer-bar-fill${isWarning ? " quiz-timer-bar-warning" : ""}`}
        style={{ width: `${pct}%` }}
      />
      <span className={`quiz-timer-label${isWarning ? " quiz-timer-label-warning" : ""}`}>
        {formatDuration(remainingSeconds)}
      </span>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Active quiz view
// ---------------------------------------------------------------------------

type ActiveQuizProps = {
  session: QuizAttemptSession;
  answers: Record<string, string | null>;
  onAnswerChange: (answers: Record<string, string | null>) => void;
  onSubmit: (
    answers: { questionUuid: string; selectedOptionUuid: string | null }[],
    options?: { timedOut?: boolean }
  ) => Promise<void>;
  isSubmitting: boolean;
  submitError: string | null;
};

function ActiveQuiz({ session, answers, onAnswerChange, onSubmit, isSubmitting, submitError }: ActiveQuizProps) {
  const getRemainingSeconds = useCallback(() => {
    if (session.expiresAt) {
      return Math.max(0, Math.ceil((new Date(session.expiresAt).getTime() - Date.now()) / 1000));
    }
    return session.timeLimitSeconds ?? null;
  }, [session.expiresAt, session.timeLimitSeconds]);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [remainingSeconds, setRemainingSeconds] = useState<number | null>(() => getRemainingSeconds());
  const timerRef = useRef<number | null>(null);
  const hasAutoSubmittedRef = useRef(false);
  // Keep a ref so the timer callback always sees latest answers
  const answersRef = useRef(answers);
  useEffect(() => { answersRef.current = answers; }, [answers]);

  // Declare handleSubmit before the timer effect so the closure reference is valid
  const handleSubmitRef = useRef<((timedOut?: boolean) => Promise<void>) | null>(null);
  const handleSubmit = useCallback(async (timedOut = false) => {
    if (timedOut && timerRef.current) window.clearInterval(timerRef.current);
    if (timedOut) {
      if (hasAutoSubmittedRef.current) return;
      hasAutoSubmittedRef.current = true;
    }
    const payload = session.questions.map((q) => ({
      questionUuid: q.questionUuid,
      selectedOptionUuid: answersRef.current[q.questionUuid] ?? null,
    }));
    await onSubmit(payload, timedOut ? { timedOut: true } : undefined);
  }, [onSubmit, session.questions]);

  useEffect(() => {
    handleSubmitRef.current = handleSubmit;
  }, [handleSubmit]);

  useEffect(() => {
    if (!session.timeLimitSeconds) {
      return;
    }
    timerRef.current = window.setInterval(() => {
      setRemainingSeconds(getRemainingSeconds());
    }, 250);
    return () => {
      if (timerRef.current) {
        window.clearInterval(timerRef.current);
        timerRef.current = null;
      }
    };
  }, [getRemainingSeconds, session.timeLimitSeconds]);

  // Trigger auto-submit after render when timer reaches 0 (not inside state updater)
  useEffect(() => {
    if (remainingSeconds === 0 && session.timeLimitSeconds && !hasAutoSubmittedRef.current) {
      void handleSubmitRef.current?.(true);
    }
  }, [remainingSeconds, session.timeLimitSeconds]);

  const currentQ: QuizSessionQuestion = session.questions[currentIndex];
  const answeredCount = Object.values(answers).filter((v) => v !== null && v !== undefined).length;
  const unansweredCount = session.questions.length - answeredCount;

  return (
    <div className="quiz-active-shell">
      {session.timeLimitSeconds && remainingSeconds !== null && (
        <TimerBar totalSeconds={session.timeLimitSeconds} remainingSeconds={remainingSeconds} />
      )}

      <div className="quiz-active-header">
        <span className="quiz-attempt-badge">尝试 #{session.attemptNumber}</span>
        <span className="quiz-progress-label">题目 {currentIndex + 1} / {session.questions.length}
        </span>
      </div>

      <div className="quiz-question-nav">
        {session.questions.map((q, i) => (
          <button
            key={q.questionUuid}
            type="button"
            className={`quiz-nav-dot${i === currentIndex ? " quiz-nav-dot-active" : ""}${answers[q.questionUuid] ? " quiz-nav-dot-answered" : ""}`}
            onClick={() => setCurrentIndex(i)}
            aria-label={`Question ${i + 1}`}
          />
        ))}
      </div>

      <div className="quiz-question-card">
        <p className="quiz-question-text">{currentQ.questionText}</p>
        <div className="quiz-options-list">
          {currentQ.options.map((opt) => {
            const selected = answers[currentQ.questionUuid] === opt.optionUuid;
            return (
              <label
                key={opt.optionUuid}
                className={`quiz-option-item${selected ? " quiz-option-item-selected" : ""}`}
              >
                <input
                  type="radio"
                  name={`q-${currentQ.questionUuid}`}
                  value={opt.optionUuid}
                  checked={selected}
                  onChange={() =>
                    onAnswerChange({ ...answers, [currentQ.questionUuid]: opt.optionUuid })
                  }
                />
                <span className="quiz-option-label-badge">{opt.optionLabel || String.fromCharCode(65 + currentQ.options.indexOf(opt))}</span>
                <span className="quiz-option-text">{opt.optionText}</span>
              </label>
            );
          })}
        </div>
      </div>

      <div className="quiz-active-nav">
        <button
          type="button"
          className="quiz-nav-btn"
          onClick={() => setCurrentIndex((i) => Math.max(0, i - 1))}
          disabled={currentIndex === 0}
        >← 上一题
        </button>
        {currentIndex < session.questions.length - 1 ? (
          <button
            type="button"
            className="quiz-nav-btn quiz-nav-btn-primary"
            onClick={() => setCurrentIndex((i) => i + 1)}
          >下一题 →
          </button>
        ) : (
          <button
            type="button"
            className="quiz-nav-btn quiz-nav-btn-primary"
            onClick={() => void handleSubmit()}
            disabled={isSubmitting}
          >
            {isSubmitting ? "提交中…" : "提交测验"}
          </button>
        )}
      </div>

      {unansweredCount > 0 && (
        <p className="quiz-unanswered-note">
          {unansweredCount} 道题尚未作答。仍可提交，未作答题目会计为错误。
        </p>
      )}

      {submitError && (
        <div className="course-management-inline-alert" style={{ marginTop: "1rem" }}>
          <strong>提交失败。</strong>
          <span>{submitError}</span>
        </div>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Result view
// ---------------------------------------------------------------------------

function ResultView({
  result,
  onRetry,
  onBack,
}: {
  result: QuizAttemptResult;
  onRetry: () => void;
  onBack?: () => void;
}) {
  const score = parseFloat(result.scorePercent);
  const passed = result.isPassed;

  return (
    <div className="quiz-result-shell">
      <div className={`quiz-result-banner${passed ? " quiz-result-banner-pass" : " quiz-result-banner-fail"}`}>
        <span className="quiz-result-icon">{passed ? "✓" : "✗"}</span>
        <div>
          <strong className="quiz-result-verdict">{passed ? "已通过" : "Not passed"}</strong>
          <p className="quiz-result-score">
            {result.correctCount} / {result.questionCount}正确 — {score.toFixed(0)}%
          </p>
          {result.isTimedOut && <p className="quiz-result-timed-out">时间已到</p>}
          {result.moduleCompleted && <p className="quiz-result-module-done">模块已标记为完成</p>}
        </div>
        <div className="quiz-result-meta">
          <span>尝试 #{result.attemptNumber}</span>
          <span>{formatDuration(result.durationSeconds)}</span>
        </div>
      </div>

      <div className="quiz-answers-list">
        {result.answers.sort((a, b) => a.questionOrder - b.questionOrder).map((ans) => (
          <div
            key={ans.questionUuid}
            className={`quiz-answer-card${ans.isCorrect ? " quiz-answer-card-correct" : " quiz-answer-card-wrong"}`}
          >
            <div className="quiz-answer-header">
              <span className={`quiz-answer-icon${ans.isCorrect ? " quiz-answer-icon-correct" : " quiz-answer-icon-wrong"}`}>
                {ans.isCorrect ? "✓" : "✗"}
              </span>
              <p className="quiz-answer-question">{ans.questionText}</p>
            </div>
            <div className="quiz-answer-detail">
              {ans.selectedOptionText ? (
                <p className={`quiz-answer-chosen${ans.isCorrect ? " quiz-answer-chosen-correct" : " quiz-answer-chosen-wrong"}`}>你的答案： {ans.selectedOptionText}
                </p>
              ) : (
                <p className="quiz-answer-chosen quiz-answer-chosen-wrong">未选择答案</p>
              )}
              {!ans.isCorrect && (
                <p className="quiz-answer-correct-opt">正确答案： {ans.correctOptionText}</p>
              )}
              {ans.explanationText && (
                <p className="quiz-answer-explanation">{ans.explanationText}</p>
              )}
            </div>
          </div>
        ))}
      </div>

      <div className="quiz-result-actions">
        {onBack ? (
          <button type="button" className="course-secondary-link" onClick={onBack}>返回历史记录
          </button>
        ) : null}
        <button type="button" className="course-primary-link" onClick={onRetry}>重试
        </button>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// History table
// ---------------------------------------------------------------------------

function HistoryTable({
  history,
  onViewAttempt,
  loadingAttemptUuid,
}: {
  history: QuizAttemptHistory;
  onViewAttempt: (quizAttemptUuid: string) => void;
  loadingAttemptUuid: string | null;
}) {
  if (history.attempts.length === 0) return null;
  return (
    <div className="quiz-history-section">
      <h3 className="quiz-history-title">历史尝试
        {history.passedOnce && <span className="quiz-passed-badge">已通过</span>}
      </h3>
      <div className="quiz-history-table">
        <div className="quiz-history-row quiz-history-row-head">
          <span>#</span><span>得分</span><span>结果</span><span>时长</span><span>日期</span>
        </div>
        {history.attempts.map((a) => (
          <button
            key={a.quizAttemptUuid}
            type="button"
            className="quiz-history-row"
            onClick={() => onViewAttempt(a.quizAttemptUuid)}
            disabled={loadingAttemptUuid === a.quizAttemptUuid}
          >
            <span>{a.attemptNumber}</span>
            <span>{parseFloat(a.scorePercent).toFixed(0)}% ({a.correctCount}/{a.questionCount})</span>
            <span className={a.isPassed ? "quiz-history-pass" : "quiz-history-fail"}>
              {a.isTimedOut ? "已超时" : a.isPassed ? "已通过" : "失败"}
            </span>
            <span>{formatDuration(a.durationSeconds)}</span>
            <span>{loadingAttemptUuid === a.quizAttemptUuid ? "加载中..." : formatDate(a.submittedAt)}</span>
          </button>
        ))}
      </div>
    </div>
  );
}

function GeneratingView({ currentStepLabel }: { currentStepLabel: string }) {
  return (
    <section className="quiz-generating-shell" aria-live="polite" aria-busy="true">
      <div className="quiz-generating-content">
        <p className="quiz-generating-text">
          {currentStepLabel}
          <span className="quiz-generating-dots" aria-hidden="true" />
        </p>
      </div>
    </section>
  );
}

// ---------------------------------------------------------------------------
// Main page
// ---------------------------------------------------------------------------

type QuizPageState = "idle" | "generating" | "active" | "result";

const GENERATION_RUN_POLL_MS = 1000;

function getGenerationRunStorageKey(courseUuid: string, moduleUuid: string) {
  return `quizGenerationRun:${courseUuid}:${moduleUuid}`;
}

function getErrorMessage(error: unknown, fallbackMessage: string) {
  return error instanceof Error && error.message.trim() ? error.message : fallbackMessage;
}

function CourseQuizPage() {
  const { moduleUuid } = useParams();
  const { course, setQuizGuard, markModuleCompleted, refreshCourse } = useOutletContext<CourseOutletContext>();
  const module = course.modules.find((m) => m.moduleUuid === moduleUuid) ?? null;
  const activeModuleUuid = module?.moduleUuid ?? null;

  const [pageState, setPageState] = useState<QuizPageState>("idle");
  const [answers, setAnswers] = useState<Record<string, string | null>>({});
  const [history, setHistory] = useState<QuizAttemptHistory | null>(null);
  const [isLoadingHistory, setIsLoadingHistory] = useState(true);
  const [session, setSession] = useState<QuizAttemptSession | null>(null);
  const [result, setResult] = useState<QuizAttemptResult | null>(null);
  const [historyResult, setHistoryResult] = useState<QuizAttemptResult | null>(null);
  const [isStarting, setIsStarting] = useState(false);
  const [toastMessage, setToastMessage] = useState<{
    title: string;
    message: string;
    variant: "success" | "error";
  } | null>(null);
  const [, setGenerationEvents] = useState<QuizGenerationProgressEvent[]>([]);
  const [currentGenerationStep, setCurrentGenerationStep] = useState<string>("Generating quiz");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);
  const [historyDetailError, setHistoryDetailError] = useState<string | null>(null);
  const [historyLoadError, setHistoryLoadError] = useState<string | null>(null);
  const [loadingAttemptUuid, setLoadingAttemptUuid] = useState<string | null>(null);
  const [generationRunId, setGenerationRunId] = useState<string | null>(null);
  const [overviewReloadKey, setOverviewReloadKey] = useState(0);
  const generationRunStorageKey = module ? getGenerationRunStorageKey(course.courseUuid, module.moduleUuid) : null;
  const pageStateRef = useRef(pageState);
  // Keep latest answers in a ref so the quiz guard callback always sees current values
  const answersRef = useRef<Record<string, string | null>>({});
  useEffect(() => { answersRef.current = answers; }, [answers]);
  useEffect(() => { pageStateRef.current = pageState; }, [pageState]);

  const applyGenerationRunStatus = useCallback((run: QuizGenerationRun) => {
    setGenerationEvents(run.events);
    if (run.currentStep) {
      setCurrentGenerationStep(getGenerationStepLabel(run.currentStep));
    } else if (run.message) {
      setCurrentGenerationStep(run.message);
    }

    if (run.status === "completed") {
      if (!run.attemptStartResponse) {
        throw new Error("Quiz generation completed without a quiz session.");
      }
      if (generationRunStorageKey) window.sessionStorage.removeItem(generationRunStorageKey);
      setGenerationRunId(null);
      setSession(run.attemptStartResponse);
      setPageState("active");
      if (activeModuleUuid) {
        emitAppRefresh({ scope: "course:quiz", courseUuid: course.courseUuid, moduleUuid: activeModuleUuid });
      }
      setToastMessage({
        title: "已恢复生成的测验。",
        message: "你生成的测验会话已准备好。",
        variant: "success",
      });
      return;
    }

    if (run.status === "failed") {
      if (generationRunStorageKey) window.sessionStorage.removeItem(generationRunStorageKey);
      setGenerationRunId(null);
      setPageState("idle");
      setToastMessage({
        title: "测验生成失败。",
        message: run.error || run.message || "请重新生成测验。",
        variant: "error",
      });
    }
  }, [activeModuleUuid, course.courseUuid, generationRunStorageKey]);

  useEffect(() => {
    setPageState("idle");
    setSession(null);
    setResult(null);
    setHistoryResult(null);
    setAnswers({});
    setToastMessage(null);
    setGenerationEvents([]);
    setCurrentGenerationStep("Generating quiz");
    setSubmitError(null);
    setHistoryDetailError(null);
    setHistoryLoadError(null);
    setLoadingAttemptUuid(null);
    setGenerationRunId(null);
  }, [moduleUuid]);

  useEffect(() => {
    if (!generationRunStorageKey || !activeModuleUuid) return;
    const storedRunId = window.sessionStorage.getItem(generationRunStorageKey);
    if (storedRunId) {
      setGenerationRunId(storedRunId);
      setPageState("generating");
      setCurrentGenerationStep("Checking generated quiz status");
      return;
    }

    let cancelled = false;
    void getActiveAutoGeneratedQuizAttemptRun(course.courseUuid, activeModuleUuid)
      .then((run) => {
        if (cancelled || !run || run.status === "failed") return;
        if (run.status === "completed") {
          applyGenerationRunStatus(run);
          return;
        }
        window.sessionStorage.setItem(generationRunStorageKey, run.runId);
        setGenerationRunId(run.runId);
        setPageState("generating");
        setCurrentGenerationStep(run.currentStep ? getGenerationStepLabel(run.currentStep) : "Checking generated quiz status");
      })
      .catch(() => {
        // No active run is fine; the normal quiz overview should render.
      });

    return () => {
      cancelled = true;
    };
  }, [activeModuleUuid, applyGenerationRunStatus, course.courseUuid, generationRunStorageKey]);

  // Reset answers when returning to idle
  useEffect(() => {
    if (pageState === "idle") setAnswers({});
  }, [pageState]);

  useEffect(() => {
    if (!toastMessage) return;
    const timer = window.setTimeout(() => setToastMessage(null), 2600);
    return () => window.clearTimeout(timer);
  }, [toastMessage]);

  useEffect(() => {
    if (!activeModuleUuid || !generationRunId || pageState !== "generating") return;

    let cancelled = false;
    let timeoutId: number | null = null;

    const pollRun = async () => {
      try {
        const run = await getAutoGeneratedQuizAttemptRun(course.courseUuid, activeModuleUuid, generationRunId);
        if (cancelled) return;
        applyGenerationRunStatus(run);
        if (run.status === "queued" || run.status === "running") {
          timeoutId = window.setTimeout(pollRun, GENERATION_RUN_POLL_MS);
        }
      } catch (err) {
        if (cancelled) return;
        const activeSession = await getActiveQuizSession(course.courseUuid, activeModuleUuid).catch(() => null);
        if (cancelled) return;
        if (activeSession) {
          if (generationRunStorageKey) window.sessionStorage.removeItem(generationRunStorageKey);
          setGenerationRunId(null);
          setSession(activeSession);
          setPageState("active");
          setToastMessage({
            title: "已恢复生成的测验。",
            message: "我们已找到你的测验会话并打开本次尝试。",
            variant: "success",
          });
          return;
        }
        if (generationRunStorageKey) window.sessionStorage.removeItem(generationRunStorageKey);
        setGenerationRunId(null);
        setPageState("idle");
        setToastMessage({
          title: "无法恢复测验生成。",
          message: err instanceof Error ? err.message : "请重新生成测验。",
          variant: "error",
        });
      }
    };

    void pollRun();

    return () => {
      cancelled = true;
      if (timeoutId !== null) window.clearTimeout(timeoutId);
    };
  }, [activeModuleUuid, applyGenerationRunStatus, course.courseUuid, generationRunId, generationRunStorageKey, pageState]);

  // Register/clear quiz guard in CourseLayout
  useEffect(() => {
    if (!activeModuleUuid) return;
    if (pageState === "active" && session) {
      setQuizGuard(true, async () => {
        const payload = session.questions.map((q) => ({
          questionUuid: q.questionUuid,
          selectedOptionUuid: answersRef.current[q.questionUuid] ?? null,
        }));
        try {
          await submitQuizAttempt(course.courseUuid, activeModuleUuid, session.attemptSessionToken, payload);
        } catch { /* ignore */ }
      });
    } else {
      setQuizGuard(false);
    }
    return () => setQuizGuard(false);
  }, [activeModuleUuid, course.courseUuid, pageState, session, setQuizGuard]);

  useEffect(() => {
    if (!activeModuleUuid) return;
    setIsLoadingHistory(true);
    setHistoryLoadError(null);
    let cancelled = false;
    Promise.allSettled([
      getQuizAttemptHistory(course.courseUuid, activeModuleUuid),
      module?.hasPublishedQuiz
        ? getActiveQuizSession(course.courseUuid, activeModuleUuid)
        : Promise.resolve(null),
    ]).then(([historyResult, activeSessionResult]) => {
      if (cancelled) return;
      if (historyResult.status === "fulfilled") {
        setHistory(historyResult.value);
      } else {
        setHistory(null);
        setHistoryLoadError(getErrorMessage(historyResult.reason, "Failed to load quiz history."));
      }

      if (activeSessionResult.status === "rejected") {
        setHistoryLoadError((current) =>
          current ?? getErrorMessage(activeSessionResult.reason, "Failed to check active quiz session.")
        );
        return;
      }

      const activeSession = activeSessionResult.value;
      if (activeSession && pageStateRef.current === "idle") {
        const wasRecoveringGeneration = generationRunStorageKey
          ? window.sessionStorage.getItem(generationRunStorageKey) !== null
          : false;
        if (generationRunStorageKey) window.sessionStorage.removeItem(generationRunStorageKey);
        setGenerationRunId(null);
        setSession(activeSession);
        setPageState("active");
        if (wasRecoveringGeneration) {
          setToastMessage({
            title: "已恢复生成的测验。",
            message: "我们已找到你的测验会话并打开本次尝试。",
            variant: "success",
          });
        }
      }
    }).finally(() => {
      if (!cancelled) {
        setIsLoadingHistory(false);
      }
    });
    return () => {
      cancelled = true;
    };
  }, [activeModuleUuid, course.courseUuid, generationRunStorageKey, module?.hasPublishedQuiz, overviewReloadKey]);

  if (!module) {
    return <Navigate to={`/course/${course.courseUuid}`} replace />;
  }

  const handleStart = async () => {
    setIsStarting(true);
    setToastMessage(null);
    try {
      const s = await startQuizAttempt(course.courseUuid, module.moduleUuid);
      setSession(s);
      setPageState("active");
      emitAppRefresh({ scope: "course:quiz", courseUuid: course.courseUuid, moduleUuid: module.moduleUuid });
    } catch (err) {
      setToastMessage({
        title: "无法开始测验。",
        message: err instanceof Error ? err.message : "Failed to start quiz.",
        variant: "error",
      });
    } finally {
      setIsStarting(false);
    }
  };

  const handleGenerate = async () => {
    setPageState("generating");
    setToastMessage(null);
    setGenerationEvents([]);
    setCurrentGenerationStep("Queued quiz generation");
    try {
      const run = await createAutoGeneratedQuizAttemptRun(course.courseUuid, module.moduleUuid);
      if (!run.runId) {
        throw new Error("Quiz generation did not return a run id.");
      }
      if (generationRunStorageKey) window.sessionStorage.setItem(generationRunStorageKey, run.runId);
      setGenerationRunId(run.runId);
    } catch (err) {
      if (generationRunStorageKey) window.sessionStorage.removeItem(generationRunStorageKey);
      setGenerationRunId(null);
      setToastMessage({
        title: "无法生成测验。",
        message: err instanceof Error ? err.message : "Failed to generate quiz.",
        variant: "error",
      });
      setPageState("idle");
    } finally {
      setGenerationEvents([]);
    }
  };

  const handleSubmit = async (
    payload: { questionUuid: string; selectedOptionUuid: string | null }[],
    options?: { timedOut?: boolean }
  ) => {
    if (!session) return;
    setIsSubmitting(true);
    setSubmitError(null);
    try {
      const r = await submitQuizAttempt(
        course.courseUuid,
        module.moduleUuid,
        session.attemptSessionToken,
        payload,
        options
      );
      if (generationRunStorageKey) window.sessionStorage.removeItem(generationRunStorageKey);
      setGenerationRunId(null);
      setResult(r);
      if (r.moduleCompleted) {
        markModuleCompleted(module.moduleUuid);
        emitAppRefresh({ scope: "course:progress", courseUuid: course.courseUuid, moduleUuid: module.moduleUuid });
      }
      setPageState("result");
      const h = await getQuizAttemptHistory(course.courseUuid, module.moduleUuid);
      setHistory(h);
      await refreshCourse();
      emitAppRefresh({ scope: "course:quiz", courseUuid: course.courseUuid, moduleUuid: module.moduleUuid });
    } catch (err) {
      setSubmitError(err instanceof Error ? err.message : "Failed to submit quiz.");
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleRetry = () => {
    setSession(null);
    setResult(null);
    setHistoryResult(null);
    setGenerationEvents([]);
    setCurrentGenerationStep("Generating quiz");
    if (generationRunStorageKey) window.sessionStorage.removeItem(generationRunStorageKey);
    setGenerationRunId(null);
    setSubmitError(null);
    setHistoryDetailError(null);
    setPageState("idle");
  };

  const handleViewAttempt = async (quizAttemptUuid: string) => {
    setHistoryDetailError(null);
    setLoadingAttemptUuid(quizAttemptUuid);
    try {
      const detail = await getQuizAttemptDetail(course.courseUuid, module.moduleUuid, quizAttemptUuid);
      setHistoryResult(detail);
    } catch (err) {
      setHistoryDetailError(err instanceof Error ? err.message : "Failed to load quiz attempt detail.");
    } finally {
      setLoadingAttemptUuid(null);
    }
  };

  return (
    <>
      {toastMessage && (
        <div
          className={`course-management-toast${
            toastMessage.variant === "error" ? " course-management-toast-error" : " course-management-toast-success"
          }`}
          role={toastMessage.variant === "error" ? "alert" : "status"}
          aria-live={toastMessage.variant === "error" ? "assertive" : "polite"}
        >
          <strong>{toastMessage.title}</strong>
          <span>{toastMessage.message}</span>
        </div>
      )}
      {pageState === "active" && session ? (
        <ActiveQuiz
          key={session.attemptSessionToken}
          session={session}
          answers={answers}
          onAnswerChange={setAnswers}
          onSubmit={handleSubmit}
          isSubmitting={isSubmitting}
          submitError={submitError}
        />
      ) : pageState === "generating" ? (
        <GeneratingView currentStepLabel={currentGenerationStep} />
      ) : pageState === "result" && result ? (
        <ResultView result={result} onRetry={handleRetry} />
      ) : historyResult ? (
        <ResultView result={historyResult} onRetry={handleRetry} onBack={() => setHistoryResult(null)} />
      ) : (
        <section className="course-detail-page">
          <div className="course-module-hero">
            <span className="course-surface-badge">测验</span>
            <h1>{history?.title ?? module.title}</h1>
            {history?.timeLimitSeconds ? (
              <p>时间限制： {formatDuration(history.timeLimitSeconds)}· 检查你对本模块的掌握情况。</p>
            ) : (
              <p>无时间限制 · 检查你对本模块的掌握情况。</p>
            )}
          </div>

          <div className="quiz-overview-body">
            <div className="quiz-overview-start-row">
              {history?.passedOnce && (
                <span className="quiz-passed-badge quiz-passed-badge-lg">已通过</span>
              )}
              <button
                type="button"
                className="course-primary-link"
                onClick={() => void handleStart()}
                disabled={isStarting}
              >
                {isStarting ? "启动中…" : history?.attempts && history.attempts.length > 0 ? "重试" : "开始测验"}
              </button>
            </div>

            {historyLoadError && (
              <div className="course-management-inline-alert" style={{ marginBottom: "1rem" }}>
                <strong>无法加载测验历史。</strong>
                <span>{historyLoadError}</span>
                <button
                  type="button"
                  className="course-secondary-link"
                  onClick={() => setOverviewReloadKey((value) => value + 1)}
                  disabled={isLoadingHistory}
                >
                  {isLoadingHistory ? "Retrying..." : "重试"}
                </button>
              </div>
            )}

            <div className="quiz-overview-generate-row">
              <button
                type="button"
                className="course-secondary-link quiz-generate-btn"
                onClick={() => void handleGenerate()}
                disabled={isStarting}
              >生成测验
              </button>
            </div>

            {historyDetailError && (
              <div className="course-management-inline-alert" style={{ marginBottom: "1rem" }}>
                <strong>无法加载尝试详情。</strong>
                <span>{historyDetailError}</span>
              </div>
            )}

            {!isLoadingHistory && history && (
              <HistoryTable
                history={history}
                onViewAttempt={handleViewAttempt}
                loadingAttemptUuid={loadingAttemptUuid}
              />
            )}
          </div>
        </section>
      )}

    </>
  );
}

export default CourseQuizPage;
