#!/usr/bin/env bash
set -euo pipefail

OUTPUT_FILE="${1:-.env.ci}"
COMPOSE_PROJECT_NAME_VALUE="${COMPOSE_PROJECT_NAME:-ai-studyplatform-ci}"

cat > "$OUTPUT_FILE" <<EOF
COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME_VALUE}
APP_ENV=ci
APP_TIMEZONE=Australia/Sydney

NGINX_PORT=18080
PUBLIC_FRONTEND_PORT=18080
FRONTEND_PORT=15173
IDENTITY_PORT=18000
AI_SERVICE_PORT=18001
COMMUNICATION_PORT=18002
LEARNING_PORT=18003
REDIS_PORT=16379
REDIS_INTERNAL_PORT=6379
QUIZ_REDIS_PORT=16380
QUIZ_REDIS_INTERNAL_PORT=6379
MINIO_API_PORT=19000
MINIO_CONSOLE_PORT=19001

VITE_API_BASE_URL=/api
IDENTITY_SERVICE_URL=http://identity-service:18000
AI_SERVICE_URL=http://ai-service:18001
COMMUNICATION_SERVICE_URL=http://communication-service:18002
LEARNING_SERVICE_URL=http://learning-service:18003
PUBLIC_BASE_URL=http://127.0.0.1:18080/api
PUBLIC_FRONTEND_URL=http://127.0.0.1:18080
INTERNAL_API_TOKEN=ci_internal_token

JWT_SECRET_KEY=ci_jwt_secret_key_replace_for_real_deployments_64_chars_minimum
JWT_ALGORITHM=HS256

MYSQL_ROOT_PASSWORD=password
MYSQL_SHARED_USER=platform_reader
MYSQL_SHARED_PASSWORD=platform_reader_password
MYSQL_INTERNAL_PORT=3306
MYSQL_PORT=13307
IDENTITY_DB_NAME=identity_db
IDENTITY_DB_USER=identity_user
IDENTITY_DB_PASSWORD=identity_password
COMMUNICATION_DB_NAME=communication_db
COMMUNICATION_DB_USER=communication_user
COMMUNICATION_DB_PASSWORD=communication_password
LEARNING_DB_NAME=learning_db
LEARNING_DB_USER=learning_user
LEARNING_DB_PASSWORD=learning_password

AI_DB_NAME=learning_platform_ai
AI_DB_USER=ai_user
AI_DB_PASSWORD=ai_password
AI_DB_PORT=5432
AI_DB_EXTERNAL_PORT=15433

AI_EMBEDDING_PROVIDER=gemini
AI_EMBEDDING_ORCHESTRATOR=langchain
AI_EMBEDDING_MODEL=gemini-embedding-001
AI_EMBEDDING_DIMENSION=1536
AI_EMBEDDING_OUTPUT_DIMENSION=1536
AI_EMBEDDING_TASK_TYPE=RETRIEVAL_DOCUMENT
AI_EMBEDDING_VERSION=gemini-embedding-001@1536
AI_EMBEDDING_BATCH_SIZE=16
AI_EMBEDDING_API_KEY=
AI_CHAT_PROVIDER=gemini
AI_CHAT_MODEL=gemini-2.5-flash-lite
AI_CHAT_BASE_URL=
AI_CHAT_API_KEY=
AI_CHAT_ORCHESTRATOR=langchain
GEMINI_API_KEY=
DEEPSEEK_API_KEY=
AI_DEMO_MODEL_NAME=gemini-2.5-flash-lite

REDIS_HOST=redis
REDIS_DB=0
CELERY_BROKER_URL=redis://redis:6379/0
CELERY_RESULT_BACKEND=redis://redis:6379/0
CELERY_TASK_ALWAYS_EAGER=false
CELERY_TASK_DEFAULT_QUEUE=ai.default
IDENTITY_CELERY_TASK_DEFAULT_QUEUE=identity.default
COMMUNICATION_CELERY_TASK_DEFAULT_QUEUE=communication.notifications
LEARNING_CELERY_TASK_DEFAULT_QUEUE=learning.quiz
CELERY_WORKER_CONCURRENCY=2
CELERY_TASK_TIME_LIMIT=300
CELERY_TASK_SOFT_TIME_LIMIT=240
CELERY_RESULT_EXPIRES=3600
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP=true
LANGGRAPH_CHECKPOINT_ENABLED=true
LANGGRAPH_CHECKPOINT_REDIS_URL=redis://redis:6379/1
LANGGRAPH_CHECKPOINT_KEY_PREFIX=ai.langgraph
QUIZ_GENERATION_RUN_REDIS_URL=redis://redis:6379/2
QUIZ_GENERATION_RUN_KEY_PREFIX=ai.quiz_generation
QUIZ_GENERATION_RUN_TTL_SECONDS=3600
QUIZ_REDIS_HOST=redis-quiz
QUIZ_REDIS_DB=0
QUIZ_REDIS_URL=redis://redis-quiz:6379/0
QUIZ_ATTEMPT_SESSION_GRACE_SECONDS=300
QUIZ_ATTEMPT_SESSION_FALLBACK_TTL_SECONDS=7200
QUIZ_ATTEMPT_SUBMIT_LOCK_SECONDS=60
QUIZ_ATTEMPT_COUNTER_TTL_SECONDS=2592000

LEARNING_MATERIAL_ROOT=/app/storage/materials
LEARNING_MATERIAL_PUBLIC_BASE_URL=/api/learning/materials
LEARNING_MATERIAL_AI_QUEUE=ai.material.index
OBJECT_STORAGE_PROVIDER=minio
MINIO_ENDPOINT=http://minio:19000
MINIO_ACCESS_KEY=minioadmin
MINIO_SECRET_KEY=minioadmin
MINIO_BUCKET=learning-materials
AI_PROFILE_BUCKET=ai-profile-assets
MINIO_PUBLIC_BASE_URL=http://127.0.0.1:18080/learning-materials
MINIO_SIGNED_URL_EXPIRES_SECONDS=300
MINIO_MULTIPART_PART_URL_EXPIRES_SECONDS=3600

SMTP_HOST=smtp.example.com
SMTP_PORT=587
SMTP_USER=ci@example.com
SMTP_PASS=ci_smtp_password
SMTP_FROM=ci@example.com
SMTP_TLS=true
VERIFY_EMAIL_PATH=/verify-email
DEFAULT_ADMIN_EMAIL=ci.admin@example.com
DEFAULT_ADMIN_PASSWORD=CiAdmin123!
DEFAULT_ADMIN_FULL_NAME=CI_Admin
EOF
