CREATE TABLE IF NOT EXISTS course_invite_tokens (
    invite_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    invite_uuid VARCHAR(36) NOT NULL,
    token_hash VARCHAR(255) NULL,
    course_id BIGINT NOT NULL,
    created_by BIGINT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    expires_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_course_invite_tokens_uuid UNIQUE (invite_uuid),
    CONSTRAINT fk_course_invite_tokens_course FOREIGN KEY (course_id) REFERENCES courses (course_id) ON DELETE CASCADE
) COMMENT='Reusable invite links for learners to self-enrol into courses, generated by educators.';
