CREATE TABLE IF NOT EXISTS short_answer_assessments (
    short_answer_assessment_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    assessment_uuid VARCHAR(36) NOT NULL,
    module_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    prompt_text TEXT NOT NULL,
    rubric_text TEXT NOT NULL,
    max_score DECIMAL(6,2) NOT NULL DEFAULT 10.00,
    status ENUM('draft', 'published', 'archived') NOT NULL DEFAULT 'draft',
    created_by BIGINT NULL,
    updated_by BIGINT NULL,
    published_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uq_short_answer_assessments_uuid UNIQUE (assessment_uuid),
    CONSTRAINT uq_short_answer_assessments_module UNIQUE (module_id),
    CONSTRAINT fk_short_answer_assessments_module FOREIGN KEY (module_id) REFERENCES modules (module_id) ON DELETE CASCADE
) COMMENT='Stores one short-answer assessment rubric per module.';

CREATE TABLE IF NOT EXISTS short_answer_submissions (
    short_answer_submission_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    submission_uuid VARCHAR(36) NOT NULL,
    assessment_id BIGINT NOT NULL,
    learner_id BIGINT NOT NULL,
    answer_text TEXT NOT NULL,
    ai_score_suggestion DECIMAL(6,2) NULL,
    ai_feedback_text TEXT NULL,
    ai_strengths_json JSON NULL,
    ai_improvements_json JSON NULL,
    ai_provider_name VARCHAR(100) NULL,
    ai_provider_model VARCHAR(160) NULL,
    final_score DECIMAL(6,2) NULL,
    final_feedback_text TEXT NULL,
    review_notes TEXT NULL,
    reviewer_id BIGINT NULL,
    reviewed_at DATETIME NULL,
    status ENUM('submitted', 'ai_suggested', 'reviewed') NOT NULL DEFAULT 'submitted',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uq_short_answer_submissions_uuid UNIQUE (submission_uuid),
    CONSTRAINT fk_short_answer_submissions_assessment FOREIGN KEY (assessment_id) REFERENCES short_answer_assessments (short_answer_assessment_id) ON DELETE CASCADE
) COMMENT='Stores learner short-answer submissions, AI suggestions, and educator final review feedback.';
